global class Constants{
	global static final String EMPTY = '';
	global static final String ERROR = 'ERROR';
	global static final String LATEST_SALESFORCE_VERSION = '64.0';
	global static final String MESSAGE = 'message';
	global static final String CUSTOM_ERROR = 'customError';
	global static final String NONE = '- Aucun -';
	global static final String STATUS = 'status';
	global static final String SUCCESS = 'SUCCESS';
	global static final String XML_HEADER = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?mso-application progid="Excel.Sheet"?>';
	@TestVisible private Constants(){} // Fix for coverage
}