global class Constants{
	global static final String EMPTY = '';
	global static final String ERROR = 'ERROR';
	global static final String LATEST_SALESFORCE_VERSION = '62.0';
	global static final String MESSAGE = 'message';
	global static final String NONE = '- Aucun -';
	global static final String STATUS = 'status';
	global static final String SUCCESS = 'SUCCESS';
	@TestVisible private Constants(){} // Fix for coverage
}