public class ExceptionConstants{
	public static final String DUPLICATES_DETECTED = 'DUPLICATES_DETECTED';
	public static final String ENTITY_IS_DELETED = 'ENTITY_IS_DELETED';
	public static final String FIELD_CUSTOM_VALIDATION = 'FIELD_CUSTOM_VALIDATION_EXCEPTION';
	public static final String INVALID_ID_FIELD = 'INVALID_ID_FIELD';
	public static final String INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST = 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST';
	public static final String UNABLE_TO_LOCK_ROW = 'UNABLE_TO_LOCK_ROW';
	public static final String UNKNOWN = 'UNKNOWN_EXCEPTION';
}