global class ProfileConstants{
	global static final String CHATTER_FREE_USER = Label.ProfileChatterFreeUser;
	global static final String CONTRACT_MANAGER = Label.ProfileContractManager;
	global static final String MARKETING_USER = Label.ProfileMarketingUser;
	global static final String STANDARD_USER = Label.ProfileStandardUser;
	global static final String SYS_ADMIN_USER = Label.ProfileSystemAdministrator;
	@TestVisible private ProfileConstants(){} // Fix for coverage
}