name: Create a Scratch Org, Push Source and Run Apex Tests

on:
  push:
    branches:
    - master
  pull_request
  
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #Check out this repo
      - name: Install SFDX CLI and authorize DevHub
        uses: apex-enterprise-patterns/setup-sfdx@v1 #We're using a fork of https://github.com/sfdx-actions/setup-sfdx for safety
        with:
          sfdx-auth-url: ${{ secrets.DEVHUB_SFDXURL }}
      - run: sfdx force:config:set defaultdevhubusername=SFDX-ENV -g #Even though the setup-sfdx action uses --setdefaultdevhubusername, it doesn't seem to stick since it uses --setdefaultusername so we brute force it here
      - run: sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername -d 1
      - run: sfdx force:source:push
      - run: sfdx force:apex:test:run -w 5
      - name: Destroy scratch org
        #Need to read more about a post action -- experimental new feature https://github.community/t5/GitHub-Actions/About-post-in-an-Action/td-p/41973
        #so that the scratch org gets deleted even if the source push or test run fails so we don't have a pileup of dysfunctional orgs
        run: sfdx force:org:delete -p
