name: check indentation | check apiVersion | run linters | run tests
run-name: ${{ github.actor }} is sending new lines of code 🚀
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

env:
  SFDX_CONSUMER_KEY: ${{ secrets.SFDX_CONSUMER_KEY }}
  SFDX_JWT_SECRET_KEY: ${{ secrets.SFDX_JWT_SECRET_KEY }}
  SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}

jobs:
  check_files_content:
    name: Check files content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Run linting of js code
        run: npm run lint:lwc && npm run lint:aura

      - name: Install SF CLI
        run: npm install -g @salesforce/cli

      - name: Run REGEX
        run: npm run regex

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run linting of apex code
        uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          sourcePath: 'force-app'
          rulesets: 'rulesets.xml'

      - name: Fail build if there are violations of apex linter
        if: steps.pmd.outputs.violations != 0
        run: exit 1
  run_tests:
    name: Create Scratch Org then run tests
    needs: check_files_content
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SF CLI
        run: npm install -g @salesforce/cli

      - name: XMLStarlet in Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          sudo ln -s /usr/bin/xmlstarlet /usr/bin/xml

      - name: Authorize DevHub
        run: |
          echo "$SFDX_JWT_SECRET_KEY" > server.key
          sf org login jwt --client-id "$SFDX_CONSUMER_KEY" --jwt-key-file server.key --username  "$SFDX_USERNAME" --alias "salesforce-tools" --set-default-dev-hub

      - name: Create Scratch Org and deploy metadata files
        run: bash scripts/initScratchOrg.sh salesforce-tools-test -s

      - name: Run tests
        id: tests
        run: bash scripts/runTests.sh --output-file

      - name: Delete Scratch Org
        run: sf org delete scratch --target-org salesforce-tools-test --no-prompt

      - name: Analyze test output
        run: |
          test_output=$(cat test_output.txt)
          echo "$test_output"

          # Check for issues in the test output
          if echo "$test_output" | grep -q -e "Class with coverage less than" -e "Class without coverage" -e "Checking if tests have failed"; then
            echo "Issues found in test coverage or failed tests."
            exit 1
          else
            echo "All tests passed and coverage is sufficient."
          fi

